anchor_scene_label_start: "Beginning of Task:"
anchor_scene_completion_start: "The scenario begins with the task completion recorded at 0%."
anchor_scene_label_middle: "Middle of Task:"
anchor_scene_completion_middle: "At the midpoint, the task completion is recorded at 50%."
anchor_scene_label_last: "End of Task:"
anchor_scene_completion_last: "The scenario concludes with the task completion recorded at 100%."
context_frame_label_template: "Sequential Frame {i}:"
context_frame_completion_template: "Task Advancement: {p}%"
eval_frame_label_template: "Assessment Frame {i}:"
eval_task_completion_instruction:
  - "For the following set of frames, which are presented out of order, you must evaluate the percentage of task completion for the goal: '{instruction}'. Adhere strictly to this response format: Frame {{i}}: Task Completion Percentages:{{}}%"
  - "Be meticulous. The percentage must accurately represent the state of completion."
  - "We remind you that the frames' order is randomized."
